Change script generation implementation
Envify-School-Project/ENVIFY-BACK pull request #10
Opened 2023-09-14 08:01 UTC by Sem-Lord

2023-09-14 08:49 UTC, PiRB commented on enfivy-back/src/main/java/com/envify/back/controller/ScriptGeneratorController.java
> +	public List<ScriptDto> getScriptLines(@RequestBody ScriptRequestBodyDto scriptRequestBody) throws EnvifyException {
Bizarre l'appellation tu mets un post mapping et tu mets get en nom de méthode c'est pas super cohérent

2023-09-15 08:59 UTC, simtaxx requested changes

2023-09-15 08:59 UTC, HarisSouici commented on enfivy-back/src/main/java/com/envify/back/controller/ScriptGeneratorController.java
> +		// get script path
Pas utile, le nom de var fait le taff

2023-09-15 08:59 UTC, simtaxx commented on enfivy-back/src/main/java/com/envify/back/controller/ScriptGeneratorController.java
> +		}
Pas be soin de if + else.
dans le if si vérifie si scriptCommand.size() est différent de scriptLabels.size() pour renvoyer une erreur, comme ça tu évites d'avoir un else en utilisant un early return.

2023-09-15 10:33 UTC, PiRB approved these changes

2023-09-17 16:34 UTC, simtaxx approved these changes

2023-09-17 18:18 UTC, merged