FEATURE: Add ConfigPackageController
Envify-School-Project/ENVIFY-BACK pull request #11
Opened 2023-09-14 10:29 UTC by simtaxx

2023-09-14 11:28 UTC, PiRB requested changes

2023-09-14 11:28 UTC, PiRB commented on enfivy-back/src/main/java/com/envify/back/controller/ConfigPackageController.java
> +@RequestMapping("/api/v1/packages")
changer l'endpoint

2023-09-14 12:39 UTC, simtaxx commented on enfivy-back/src/main/java/com/envify/back/controller/ConfigPackageController.java
> +@RequestMapping("/api/v1/packages")
Too late already done mister brivio

2023-09-14 13:00 UTC, PiRB approved these changes

2023-09-15 08:47 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/entity/ConfigPackageEntity.java
> +    @Column(name = "config_id", nullable = false)
Erreur le config id est pas auto incrémenter. c'est une clé étrangère de la table config. t'aura une erreur au moment du save dans le controller. faut que tu utilise l'annotation adéquate.

2023-09-15 08:50 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/entity/ConfigPackageEntity.java
> +    public int getPackageVersionId() {
C'est une clé étrangère aussi faut utiliser la bonne annotation

2023-09-15 08:52 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/service/impl/ConfigPackageServiceImpl.java
> +    public void saveConfigPackage(ConfigPackageEntity configPackageEntity) {
Pour le save on à besoin de id de config et de package sinon on risque d'avoir des modifs sur plusieurs lignes. faut modifier la méthode

2023-09-15 08:53 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/controller/ConfigPackageController.java
> +        mapConfigPackageDtoToConfigPackageEntity(configPackageDto, configPackageUpdated, id);
on utilise mapstruct pour faire le mapping. tu peux faire un rebase de master et l'utiliser

2023-09-15 09:08 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/controller/ConfigPackageController.java
> +        configPackageCreated.setPackageVersionId(configPackageEntityDto.getPackageVersionId());
Il manque le set du config qui est une clé primaire. Le save va fail et renvoyer une bad request exception

2023-09-15 09:12 UTC, Sem-Lord commented on enfivy-back/src/main/java/com/envify/back/controller/ConfigPackageController.java
> +        ConfigPackageEntity packageEntity = configPackageService.findConfigPackageById(id);
Le get devrait être fait en utilisant les deux clés primaires

2023-09-20 21:39 UTC, closed without merging